### ISSUE TITLE
causes conflicts with other widgets 

### ISSUE THREAD

**Issue by veonua** [MicrosoftDocs/MachineLearning-Python-Feedback#15]
for some reason this plugin redefines JQuery, so other plugins that uses Jquery-ui and other plugins fail to run properly

conflicts with QGrid and others

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 495e49aa-981c-4080-78f9-e242470b6d98
* Version Independent ID: 28a6235e-8de1-766a-df28-16769c441546
* Content: [azureml-train-widgets package](https://docs.microsoft.com/en-us/python/api/azureml-train-widgets/?view=azure-ml-py)
* Content Source: [AzureML/docs-ref-autogen/azureml-train-widgets/index.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML/docs-ref-autogen/azureml-train-widgets/index.yml)
* Service: **machine-learning**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by akshaya-a** [comment]
@veonua Thanks for the report! We'll investigate this issue and report back

**Comment by veonua** [comment]
any browser. I can see jQuery UI is not defined because this plugin redefines jQuery WITHOUT jQuery UI

**Comment by ahcan76** [comment]
We tried loading the AML widget and QGrid widget in a sample notebook in various combinations. We were able to see both widgets loading in the notebook. Yes, we can see in the console that the jquery object's "ui" property is set to null when we load the AML widget (that's because AML widget does not use jquery-ui), but the "ui" property is reset by QGrid when the QGrid widget is being loaded.  Hence, we can't repro the failures in our sample notebook and need additional data to further drill down. Could you send output of "jupyter nbextension list" and "pip freeze" commands. We want to see whether there are other extensions you might have which may contribute to the issue.

**Comment by veonua** [comment]
Were you able to actually use QGrid with AML?
I removed AML so far but it would be fairly easy to reproduce as soon as I
got this conflict in Azure ML Virtual Machine

**Comment by ahcan76** [comment]
yes, we were able to run both widgets on our local jupyter instances. Also we just tried on a AzureML DSVM. AML widgets are already deployed there; additionally we installed QGrid. And we are still able to load both widgets in the same notebook. Could you provide the output of the above commands (from my previous post) from your DSVM?

**Comment by veonua** [comment]
it seems new DSVM does not have the plugin preistalled.
at least my recent VM has

```
jupyter nbextension list
Known nbextensions:
  config dir: /anaconda/envs/py35/etc/jupyter/nbconfig
    notebook section
      nb_conda/main  enabled 
      - Validating: OK
      nbpresent/js/nbpresent.min  enabled 
      - Validating: OK
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
      qgrid/extension  enabled 
      - Validating: OK
      plotlywidget/extension  enabled 
      - Validating: OK
    tree section
      nb_conda/tree  enabled 
      - Validating: OK
```

unfortunately I don't even remember exact name of AML google finds "Anti-money laundering – Microsoft Azure helping banks reduce false positives"
